stages:
  - .pre
  - build
  - build test
  - deploy staging
  - deploy production

variables:
  APP_VERSION: $CI_PIPELINE_IID

build website:
  stage: build
  image: node:16-alpine
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
    - echo $APP_VERSION > build/version.html
  artifacts:
    paths:
      - build

test website:
  stage: build test
  image: node:16-alpine
  script:
    - yarn global add serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"

.deploy:
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo $CI_COMMIT_REF_NAME
    - aws s3 sync build s3://$AWS_S3_BUCKET/ --delete
    - curl $CI_ENVIRONMENT_URL | grep "React App"
    - curl $CI_ENVIRONMENT_URL/version.html | grep $APP_VERSION

deploy staging:
  stage: deploy staging
  environment: staging
  extends: .deploy

deploy production:
  stage: deploy production
  when: manual
  environment: production
  extends: .deploy